"""Minimal single-sample Hugging Face runner for the EOPD objective.

It follows Baselines/EOPD's on-policy loss: clipped reverse-KL policy-gradient
term plus entropy-gated top-k forward KL. The rollout is generated by the
current student, while the teacher stays frozen and may be sharded across GPUs.
"""

import argparse
import json
import os
import random

import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer

from cache_eopd.train_student_distill import load_teacher_sharded


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--student", required=True)
    parser.add_argument("--teacher", required=True)
    parser.add_argument("--data-path", required=True)
    parser.add_argument("--device", default="cuda:1")
    parser.add_argument("--teacher-gpus", default="2,3")
    parser.add_argument("--dtype", default="bfloat16")
    parser.add_argument("--max-prompt-len", type=int, default=384)
    parser.add_argument("--max-new-tokens", type=int, default=256)
    parser.add_argument("--steps", type=int, default=300)
    parser.add_argument("--lr", type=float, default=1e-6)
    parser.add_argument("--topk", type=int, default=32)
    parser.add_argument("--entropy-threshold", type=float, default=0.8)
    parser.add_argument("--soft-kd-coef", type=float, default=1.0)
    parser.add_argument("--clip-ratio", type=float, default=0.2)
    parser.add_argument("--save-every", type=int, default=100)
    parser.add_argument("--log-every", type=int, default=1)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--seed", type=int, default=0)
    return parser.parse_args()


def render_prompt(tokenizer, text):
    messages = [{"role": "user", "content": text}]
    try:
        rendered = tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True, enable_thinking=False
        )
    except TypeError:
        rendered = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    token_ids = tokenizer(rendered, add_special_tokens=False)["input_ids"]
    return token_ids[-len(token_ids) :]


def log_probs_for_labels(logits, labels):
    return F.log_softmax(logits.float(), dim=-1).gather(-1, labels.unsqueeze(-1)).squeeze(-1)


@torch.no_grad()
def teacher_signals(teacher, sequence, prompt_len, topk):
    teacher_device = teacher.get_input_embeddings().weight.device
    inputs = sequence.to(teacher_device)
    output = teacher(input_ids=inputs, attention_mask=torch.ones_like(inputs), use_cache=False)
    response_logits = output.logits[:, prompt_len - 1 : -1]
    response_labels = inputs[:, prompt_len:]
    full_log_probs = F.log_softmax(response_logits.float(), dim=-1)
    teacher_log_probs = full_log_probs.gather(-1, response_labels.unsqueeze(-1)).squeeze(-1)
    teacher_entropy = -(full_log_probs.exp() * full_log_probs).sum(dim=-1)
    topk_logits, topk_indices = torch.topk(response_logits.float(), k=topk, dim=-1)
    teacher_topk_log_probs = F.log_softmax(topk_logits, dim=-1)
    return (
        teacher_log_probs,
        teacher_entropy,
        teacher_topk_log_probs,
        topk_indices,
    )


@torch.no_grad()
def student_old_log_probs(student, sequence, prompt_len):
    output = student(
        input_ids=sequence,
        attention_mask=torch.ones_like(sequence),
        use_cache=False,
    )
    response_logits = output.logits[:, prompt_len - 1 : -1]
    labels = sequence[:, prompt_len:]
    return log_probs_for_labels(response_logits, labels).detach()


def save_student(student, tokenizer, path):
    os.makedirs(path, exist_ok=True)
    student.save_pretrained(path, safe_serialization=True)
    tokenizer.save_pretrained(path)


def main():
    args = parse_args()
    torch.manual_seed(args.seed)
    random.seed(args.seed)
    os.makedirs(args.out_dir, exist_ok=True)
    dtype = getattr(torch, args.dtype)
    student = AutoModelForCausalLM.from_pretrained(
        args.student, torch_dtype=dtype, attn_implementation="sdpa"
    ).to(args.device)
    student_device = torch.device(args.device)
    teacher_gpus = [int(value) for value in args.teacher_gpus.split(",") if value]
    teacher = load_teacher_sharded(args.teacher, dtype, teacher_gpus, attn_impl="sdpa")
    tokenizer = AutoTokenizer.from_pretrained(args.student)
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token
    with open(args.data_path, encoding="utf-8") as handle:
        rows = [json.loads(line) for line in handle if line.strip()]
    if not rows:
        raise ValueError("data file is empty")
    optimizer = torch.optim.AdamW(student.parameters(), lr=args.lr)
    eos_ids = {tokenizer.eos_token_id}
    if isinstance(student.generation_config.eos_token_id, list):
        eos_ids.update(student.generation_config.eos_token_id)
    log_path = os.path.join(args.out_dir, "train_log.jsonl")
    with open(log_path, "w", encoding="utf-8") as log_handle:
        for step in range(1, args.steps + 1):
            row = rows[(step - 1) % len(rows)]
            prompt_ids = render_prompt(tokenizer, row["prompt"])
            prompt_ids = prompt_ids[-args.max_prompt_len :]
            prompt = torch.tensor(prompt_ids, dtype=torch.long, device=student_device).unsqueeze(0)
            student.eval()
            with torch.no_grad():
                generated = student.generate(
                    input_ids=prompt,
                    attention_mask=torch.ones_like(prompt),
                    do_sample=True,
                    temperature=1.0,
                    top_p=1.0,
                    max_new_tokens=args.max_new_tokens,
                    eos_token_id=list(eos_ids),
                    pad_token_id=tokenizer.pad_token_id,
                )
            response = generated[:, prompt.shape[1] :]
            if response.shape[1] == 0:
                continue
            sequence = torch.cat([prompt, response], dim=1)
            prompt_len = prompt.shape[1]
            old_log_probs = student_old_log_probs(student, sequence, prompt_len)
            teacher_log_probs, teacher_entropy, teacher_topk_log_probs, topk_indices = teacher_signals(
                teacher, sequence, prompt_len, args.topk
            )
            student.train()
            output = student(input_ids=sequence, attention_mask=torch.ones_like(sequence), use_cache=False)
            response_logits = output.logits[:, prompt_len - 1 : -1]
            current_log_probs = log_probs_for_labels(response_logits, response)
            teacher_log_probs = teacher_log_probs.to(student_device)
            teacher_entropy = teacher_entropy.to(student_device)
            teacher_topk_log_probs = teacher_topk_log_probs.to(student_device)
            topk_indices = topk_indices.to(student_device)
            student_full_log_probs = F.log_softmax(response_logits.float(), dim=-1)
            student_topk_log_probs = student_full_log_probs.gather(-1, topk_indices)
            response_mask = torch.ones_like(current_log_probs)
            advantage = (teacher_log_probs - old_log_probs).detach()
            ratio = torch.exp(current_log_probs - old_log_probs)
            clipped_ratio = torch.clamp(ratio, 1 - args.clip_ratio, 1 + args.clip_ratio)
            pg_loss = torch.maximum(-advantage * ratio, -advantage * clipped_ratio).mean()
            soft_mask = (teacher_entropy >= args.entropy_threshold).float() * response_mask
            teacher_probs = teacher_topk_log_probs.exp()
            kl = (teacher_probs * (teacher_topk_log_probs - student_topk_log_probs)).sum(dim=-1)
            soft_kd_loss = (kl * soft_mask).sum() / response_mask.sum().clamp_min(1.0)
            loss = pg_loss + args.soft_kd_coef * soft_kd_loss
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            grad_norm = torch.nn.utils.clip_grad_norm_(student.parameters(), 1.0)
            optimizer.step()
            record = {
                "step": step,
                "loss": float(loss.detach().cpu()),
                "pg_loss": float(pg_loss.detach().cpu()),
                "soft_kd_loss": float(soft_kd_loss.detach().cpu()),
                "teacher_entropy": float(teacher_entropy.mean().detach().cpu()),
                "soft_kd_token_ratio": float(soft_mask.mean().detach().cpu()),
                "response_len": int(response.shape[1]),
                "grad_norm": float(grad_norm.detach().cpu()),
            }
            if step % args.log_every == 0:
                print(json.dumps(record), flush=True)
                log_handle.write(json.dumps(record) + "\n")
                log_handle.flush()
            if step % args.save_every == 0 or step == args.steps:
                save_student(student, tokenizer, os.path.join(args.out_dir, f"step{step}"))


if __name__ == "__main__":
    main()
